### ISSUE TITLE
Improve visibility and coverage of examples

### ISSUE THREAD

**Issue by dannyrb** [cornerstonejs/cornerstoneTools#909]
Re: https://github.com/cornerstonejs/cornerstoneTools/issues/906

The first thing a would-be user looks for when coming to the `cornerstone-tools` repository are examples of _what is possible_. Being able to see and play with the library immediately conveys its value and provides minimal reproductions for how to accomplish `X feature`.

Currently, to find out examples, you need to:

- Click [`Read The Docs`](https://tools.cornerstonejs.org/) at the top of our [README.md](https://github.com/cornerstonejs/cornerstoneTools/blob/master/README.md)
- Notice and click the [`Examples` Link](https://tools.cornerstonejs.org/examples/) in the [documentation sidebar](https://tools.cornerstonejs.org/)

Even then, a large number of examples that were available in `v2` are not present.

This micro examples are nice, but it's also important to be able to see how they can be used together. Some of our most important features require a viewer-like setup. We already use the [`index.html`](https://github.com/cornerstonejs/cornerstoneTools/blob/master/index.html) in our root folder as a quick test for [pull-requests](https://deploy-preview-908--cornerstone-tools.netlify.com/), but it can be cleaned up and made more accessible.

### Tasks

- [ ] "How To" add/test examples
- [ ] 1:1 examples of tools from v2 --> v3
- [ ] Live Demo of a simple viewer made w/ `cornerstone-tools`
    - [ ] Use a hyperlinked GIF + caption to call attention to demo
- [ ] Fully Featured demo of advanced viewer made w/ `cornerstone-tools` (OHIF)
- [ ] CodeSandbox.io template

### 👋 Hello
 
This is a small list of the most pressing documentation items I believe we need to address. If there's something you would like to grab or would like guidance on, please let me know.

After we tackle these, we can move on to other high value items like the GitBook guide ^_^
